### PR TITLE
A bunch of tweaks and fixes again

### PR DESCRIPTION
**Pull request by NeoDement**
World Wrap:

-Fixed a bug where fake hands wouldn't automatically delete themselves if there were no creatures in the world

Nut:

-Attempted to fix an invalid targ error using INST
-Moved the FRAT commands to the Constructor Script (to prevent a potential runtime error)
-Fixed the nut death anim being 1 frame too long.

Pump:

-Moved FRAT commands into the Constructor Script to stop a runtime error

### CODE REVIEW

**Comment by NeoDement** [comment]
Barnacles:

-Moved an ATTR change (enabling physics) from the Drop script to the Pickup script to hopefully have the same effect but prevent an invalid map position error.

Foghorn:

-Made the foghorn pickupable
-Added a hit script
-Fixed some potential FRAT issues

Nut:

-Slightly more robust nut targ fix (moved an OV check to its own line to stop NULL TARGs causing an error)

Submarine:

-Gave it a higher plane to stop it intersecting the Ball
-Disabled the button hover anim because it didn't work very well
-Moved all FRAT commands to install script to fix a possible runtime error

**Comment by NeoDement** [comment]
Lifts:

-A bunch of changes to make the hit script more reliable and work on both types of buttons

**Comment by NeoDement** [comment]
World Wrap:

-The camera tracking offset fix is applied to any object the camera is tracking instead of just creatures that are holding the hand.
-Changed how the hand-speak on the other side of the wrap is sent. The ORDR SHOU command is now sent from the real hand in a temporary location during an INST command.
-Objects and the pointer will no longer transport through the wrap if they have a creatures attention on them. Left or right click immediately overrides this for the pointer so you can still interact with things as expected.
-The hand speech grabber now takes the X coordinate of the speech bubble into account instead of just Y.

**Comment by NeoDement** [comment]
Lifts:

-Finally added missing metal platform lift in labs
-Lift parts and buttons are now automatically created according to OV04 instead of having to be manually created each time
-Moved lift buttons on plain wooden lifts to match C2 position
-Lifts now stop precisely at the Y pos of each stop instead of an approximation based on their movement speed
-Commented out debug text part creation
-Redrew the up and down buttons used on the wooden lifts to match the fidelity of the rest of the world. Previously they were using some ancient C1 leftover.

Overlays:

-Fixed incorrect (too high) planes on a few background overlays.
-Also removed a background overlay from the lab that was no longer required as it wasn't animated and should be drawing behind everything anyway.

World Wrap (optimization):

-Using AVAR instead of numerically named NAME variables. This means we are using the existing OVs instead of creating new NAME variables every few ticks, and means the script doesn't have to switch TARG so frequently. Minor caveat is that the wrap script will now only track up to 100 creatures IITTs at a time instead of potentially infinite, but seeing as the game grinds to a crawl at about 60 creatures, the trade-off seems worth it.

**Comment by NeoDement** [comment]
Anthill:

-Moved an AND condition to a separate line from a null check, to allow the null check to actually work. This should fix a "decimal expected" error.

Lift Call Button:

-Moved INST to the very beginning of the Activate 1 and 2 scripts, just in case. This _might_ fix an "Invalid TARG" error.

**Comment by NeoDement** [comment]
Tomatoes: 

-Tomatoes can decay in vehicles (but not when being held by the hand or creatures). They will still die when they fail the CA check instead of growing into a new plant in the vehicle.
-Moved FRAT to Constructor Scripts instead of just before ANIM, just in case.

Incubator:

-Added Open Air Cabin attribute so norns can take out things they put in. This won't apply to eggs, it's intended to stop them dropping toys or food in there and immediately losing sight of it.

Genetic Splicer:

-Pods now automatically eject anything that isn't a creature if it's dropped in the pod.
-They also automatically eject extra creatures if you try and drop them in a pod that already contains at least one creature.

Bluebirds:

-Removed an unused, buggy variable assignment that rarely caused a "Negative Square Root" crash.
-Rounded some floats to ints before a MVSF. Hopefully this stops a weird error where the coords returned are "1.#QNAN0".
-Fixed a potential invalid TARG error when checking if seeds exist in bluebird timer script.

World Wrap (more optimizations):

-Each grabber valid targ object check is now done in it's own block instead of all on one line, as the engine tries to check all of them at once instead of doing them in sequence. This should mean we're doing less redundant checks per tick.
-Replaced "Left" and "Right" strings with LEFT and RGHT constants. Checking a string value every tick is probably expensive.

**Review by Amaikokonut — APPROVED** [review]

**Pull request merged**
