### PR TITLE
A bunch of fixes and improvements

### PR DESCRIPTION
**Pull request by NeoDement**
Aubergine:

- Fixed low gravity on detritus

Helicopter:

- Fixed heli being categorized as a Teleporter
- Changed heli to pick up creatures as it takes flight instead of requiring a seperate press on the body of the vehicle.
- Added some chemical reductions to make it fun for creatures to ride
- Fixed an issue where the heli ACCG would end up way too high after flying once

### CODE REVIEW

**Comment by NeoDement** [comment]
Punching Bag:

-Enabled picking up punching bags
-Tweaked the hands left-sided slap anim to match the right one more closely.
-Fixed mirrored sprites for the punching bag. The green and blue parts don't magically switch positions when it gets smacked to the left anymore.

**Comment by NeoDement** [comment]
Cheese Machine:

-Sped the machine up a bit and fixed it so the fake cheese and the real cheese are never on screen at the same time.

**Comment by NeoDement** [comment]
Fountain (Seltzer Water Bottle)

- Enabled picking up fountains.
- Cleaned up unused script numbers.
- Made spray anim match the C2 one more precisely.
- The fountain can be rotated in mid-air like the tomato launcher.

**Comment by NeoDement** [comment]
made the main teleporter in the Incubator Room pickupable, to match it's counterpart in the Workshop

**Comment by NeoDement** [comment]
C2 Hand:

-Fixed to not show a Red NO Circle when dropping an object with collisions disabled outside the room system.


Weather:

-INST'd creation of dust devils to fix a rare bug

**Comment by NeoDement** [comment]
Slinky:

-Adjusted animation speed to match C2 spring better
-Added a PUHL

**Review by Amaikokonut — APPROVED** [review]

**Pull request merged**
