### PR TITLE
Genetic Splicer, Door Fixes, Chimes Toy, Incubator Tweaks, Overlay Fixes, Temporary Map Tweaks, Helicopter ACCG Tweak

### PR DESCRIPTION
**Pull request by NeoDement**
the coolest machine in town

### CODE REVIEW

**Comment by NeoDement** [comment]
Genetic Splicer:
-Added the Genetic Splicer

Door Fixes:
-Fixed some issues with the volcano door sprite (the entire door no longer moves down 1px while fully closed)
-Fixed backwards logic in Terrarium Door open/close script.
-Moved FRAT commands into the creation scripts instead of just before animating. Also changed the water from FRAT 3 to FRAT 2 for consistency with the other anims.

**Comment by NeoDement** [comment]
Genetic Splicer:
-Added the Genetic Splicer

Door Fixes:
-Fixed some issues with the volcano door sprite (the entire door no longer moves down 1px while fully closed)
-Fixed backwards logic in Terrarium Door open/close script.
-Moved FRAT commands into the creation scripts instead of just before animating. Also changed the water from FRAT 3 to FRAT 2 for consistency with the other anims.

Chimes Toy:
-It's near the frog pond

**Comment by NeoDement** [comment]
-TEMPORARY: Removed a bunch of useless rooms underground that objects and norns were getting stuck in. Also changed the permeability on some ledges to stop norns drowing themselves.

-Fixed the framerates and anims on a bunch of world over/underlays to match C2 more precisely. Also fixed incubator waterfall plane.

-Fixed the terrarium door again (idk what happened)

-Made the incubator pickupable by the hand, gave it some physics, stopped it being possible to grab eggs mid-hatching and fixed up the framerate.

-Helicopter falls slower, but it still falls through the bridge and volcano for now.

**Comment by NeoDement** [comment]
-Terrarium Door now really really works properly (bug was caused by night switcher cos)

**Review by Amaikokonut — APPROVED** [review]
Incredible work <3

**Pull request merged**
