### PR TITLE
Doozers, Shee Laptop, World Wrap Improvements, Music Manager + Various Tweaks

### PR DESCRIPTION
**Pull request by NeoDement**
Doozers:

-Added Doozers!

Pop Rocket:

-Very slight changes to make it easier to use script 1000 in other objects that might need to check if any of the objects sprite bounds intersect with an impermeable wall (such as the Doozer)

### CODE REVIEW

**Comment by NeoDement** [comment]
Doozers:

-Now always play an eat sound when eaten instead of only if being held by a creature
-Changed eat sound

**Comment by NeoDement** [comment]
Doozers:

-Removed some leftover code which attempted to dynamically created a talk anim of the appropriate length (speech bubbles ALWAYS stay onscreen for 20 ticks regardless of string length)

**Comment by NeoDement** [comment]
Doozers:

-removed unused va61

**Comment by NeoDement** [comment]
Shee Laptop:

-added shee laptop! teaches 5 whole words.

Water Pumps:

-removed duplicate eat script and increased PLNE

Guitar:

-Removed random PLNE, now it's always 3500. Previously it could be up to 50000 which drew in front of literally everything.

Fishbowls:

-moved to their respective seas
-moved the fishbowls out of the incubator room and into their respective seas
-lowered the plane and removed randomness

**Comment by NeoDement** [comment]
Added three colour variations of the font from C2:

moe_C2toDS_Font_Speech.c16 - Used by the C2 speech/thought bubbles
moe_C2toDS_Font_ComputerGreen.c16 - Used by the verbs computer
moe_C2toDS_Font_ComputerBlue.c16 - Used by the adjectives computer

**Comment by NeoDement** [comment]
Music Manager:
-Overrides standard Near Death, Death and Birth music with Creatures 2 equivalents.

World Wrap:
-Creatures can hear Hand and Agent Help speech over wrap. WIP.

Doozers:
-Added slight variance in initial tick rate, so they don't all go HUP at the same time.

**Review by Amaikokonut — APPROVED** [review]

**Pull request merged**
